#!/usr/bin/env bash
# Infinite loop printing "To infinity and beyond"; responds to SIGTERM with "I am invincible!!!"
trap 'echo "I am invincible!!!"' SIGTERM; while true; do echo "To infinity and beyond"; sleep 2; done
