#!/usr/bin/env bash
# Display different messages for 4th and 8th iterations, else "Best School"
count=1; while [ $count -le 10 ]; do [ $count -eq 4 ] && echo "bad luck" || [ $count -eq 8 ] && echo "good luck" || echo "Best School"; ((count++)); done
