#!/usr/bin/env bash
# Check properties of a file named school and display corresponding messages
[ -e school ] && { echo "school file exists"; [ -s school ] && echo "school file is not empty" || echo "school file is empty"; [ -f school ] && echo "school is a regular file"; } || echo "school file does not exist"
